Fix an issue querying task results in the case of an unfinished task
Without the patch this is what you get when you query a task that is processing:

    {"error"=>"AttributeError", "detail"=>"", "body"=>"", "errors"=>"'str' object has no attribute 'value'"}

This is because the task.status object in the patched line is a string,
so it has no `value` property.